COMMENT

   **************************************************
   File automatically generated by: neuroConstruct 
   **************************************************

   This file holds the implementation in NEURON of the Cell Process:
   KConductance (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@xsi:schemaLocation = http://morphml.org/channelml/schema  ../../Schemata/v1.1/Level2/ChannelML_v1.1.xsd 
   /channelml/@units = Physiological Units 
   /channelml/notes/. = null 
   /channelml/ion/@name = k 
   /channelml/ion/@default_erev = -77.0 
   /channelml/ion/@charge = 1 
   /channelml/channel_type/@name = KConductance 
   /channelml/channel_type/@density = yes 
   /channelml/channel_type/notes/. = null 
   /channelml/channel_type/notes/. = null 
   /channelml/channel_type/notes/. = null 
   /channelml/channel_type/current_voltage_relation/ohmic/@ion = k 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/@default_gmax = 36 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/@power = 4 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/@name = n 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/@fraction = 1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/alpha/parameterised_hh/@type = linoid 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/alpha/parameterised_hh/@expr = A*(k*v-d)/(1 - exp(-(k*v-d))) 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@value = 0.1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@value = 0.1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@value = -55 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/beta/parameterised_hh/@type = exponential 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/beta/parameterised_hh/@expr = A*exp(k*(v-d)) 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@value = 0.125 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@value = -0.0125 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@value = -65 

ENDCOMMENT


?  This is a NEURON mod file generated from a v1.1 ChannelML file

?  Unit system of ChannelML file: Physiological Units


COMMENT
    ChannelML file containing a single Channel description
ENDCOMMENT

TITLE Channel: KConductance

COMMENT
    Simple example of K conductance in squid giant axon. Based on:
        A. L. Hodgkin and A. F. Huxley, A quantitative description of membrane current and its application 
        to conduction and excitation in nerve, J. Physiol., vol. 117, pp. 500-544, 1952.
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
}


    
NEURON {
    SUFFIX KConductance
    USEION k READ ek WRITE ik
    RANGE gmax, gion
    
    RANGE ninf, ntau
    
}

PARAMETER { 
    gmax = 0.036 (S/cm2) 
    
}



ASSIGNED {
    v (mV)
    
    celsius (degC)
    
    ek (mV)
    ik (mA/cm2)
    
    gion (S/cm2)
    ninf
    ntau (ms)
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    gion = gmax*((1*n)^4)
    ik = gion*(v - ek)
            
}
    

INITIAL {

    ek = -77.0
    rates(v)
    n = ninf
    
}
    
STATE {
    n
    
}

DERIVATIVE states {
    rates(v)
    n' = (ninf - n)/ntau
    
}

 
PROCEDURE rates(v(mV)) {
    
    ? Note, not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, A, B, k, d, tau, inf, temp_adj  
    
    ? May be too many table points and too wide a range...
    TABLE ninf, ntau DEPEND celsius FROM -100 TO 100 WITH 400
    
    
    UNITSOFF
    
    temp_adj = 1
        
    
    ? Adding rate equations for gate: n
    
    ? Found a parameterised form of rate equation for alpha, using expression: A*(k*v-d)/(1 - exp(-(k*v-d)))
    A = 0.1
    k = 0.1
    d = -55
    
    B = 1/k 
    
    alpha = A * vtrap((v - d), B)
    
    
    ? Found a parameterised form of rate equation for beta, using expression: A*exp(k*(v-d))
    A = 0.125
    k = -0.0125
    d = -65
    
    B = 1/k 
    
    beta = A * exp((v - d) / B)
    
    ntau = 1/(temp_adj*(alpha + beta))
    ninf = alpha/(alpha + beta)
        
       
    
    ? Finished rate equations for gate: n
}

FUNCTION vtrap(VminV0, B) {
    if (fabs(VminV0/B) < 1e-6) {
    vtrap = (1 + VminV0/B/2)
}else{
    vtrap = (VminV0 / B) /(1 - exp((-1 *VminV0)/B))
    }
}

UNITSON


