COMMENT

   **************************************************
   File automatically generated by: neuroConstruct 
   **************************************************

   This file holds the implementation in NEURON of the Cell Process:
   NaConductance (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@xsi:schemaLocation = http://morphml.org/channelml/schema  ../../Schemata/v1.1/Level2/ChannelML_v1.1.xsd 
   /channelml/@units = Physiological Units 
   /channelml/notes/. = null 
   /channelml/ion/@name = na 
   /channelml/ion/@charge = 1 
   /channelml/ion/@default_erev = 50 
   /channelml/channel_type/@name = NaConductance 
   /channelml/channel_type/@density = yes 
   /channelml/channel_type/notes/. = null 
   /channelml/channel_type/notes/. = null 
   /channelml/channel_type/notes/. = null 
   /channelml/channel_type/current_voltage_relation/ohmic/@ion = na 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/@default_gmax = 120 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/@power = 3 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/@name = m 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/@fraction = 1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/alpha/parameterised_hh/@type = linoid 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/alpha/parameterised_hh/@expr = A*(k*v-d)/(1 - exp(-(k*v-d))) 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@value = 1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@value = 0.1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@value = -40 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/beta/parameterised_hh/@type = exponential 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/beta/parameterised_hh/@expr = A*exp(k*(v-d)) 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@value = 4 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@value = -0.0555555555 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@value = -65 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/@power = 1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/@name = h 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/@fraction = 1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/alpha/parameterised_hh/@type = exponential 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/alpha/parameterised_hh/@expr = A*exp(k*(v-d)) 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@value = 0.07 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@value = -0.05 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@value = -65 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/beta/parameterised_hh/@type = sigmoid 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/beta/parameterised_hh/@expr = A/(1 + exp(-k*(d-v))) 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@value = 1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@value = -0.1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@value = -35 

ENDCOMMENT


?  This is a NEURON mod file generated from a v1.1 ChannelML file

?  Unit system of ChannelML file: Physiological Units


COMMENT
    ChannelML file containing a single Channel description
ENDCOMMENT

TITLE Channel: NaConductance

COMMENT
    Simple example of Na conductance in squid giant axon. Based on:
        A. L. Hodgkin and A. F. Huxley, A quantitative description of membrane current and its application 
        to conduction and excitation in nerve, J. Physiol., vol. 117, pp. 500-544, 1952.
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
}


    
NEURON {
    SUFFIX NaConductance
    USEION na READ ena WRITE ina
    RANGE gmax, gion
    
    RANGE minf, mtau
    
    RANGE hinf, htau
    
}

PARAMETER { 
    gmax = 0.12 (S/cm2) 
    
}



ASSIGNED {
    v (mV)
    
    celsius (degC)
    
    ena (mV)
    ina (mA/cm2)
    
    gion (S/cm2)
    minf
    mtau (ms)
    hinf
    htau (ms)
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    gion = gmax*((1*m)^3)*((1*h)^1)
    ina = gion*(v - ena)
            
}
    

INITIAL {

    ena = 50
    rates(v)
    m = minf
    h = hinf
    
}
    
STATE {
    m
    h
    
}

DERIVATIVE states {
    rates(v)
    m' = (minf - m)/mtau
    h' = (hinf - h)/htau
    
}

 
PROCEDURE rates(v(mV)) {
    
    ? Note, not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, A, B, k, d, tau, inf, temp_adj  
    
    ? May be too many table points and too wide a range...
    TABLE minf, mtau,hinf, htau DEPEND celsius FROM -100 TO 100 WITH 400
    
    
    UNITSOFF
    
    temp_adj = 1
        
    
    ? Adding rate equations for gate: m
    
    ? Found a parameterised form of rate equation for alpha, using expression: A*(k*v-d)/(1 - exp(-(k*v-d)))
    A = 1
    k = 0.1
    d = -40
    
    B = 1/k 
    
    alpha = A * vtrap((v - d), B)
    
    
    ? Found a parameterised form of rate equation for beta, using expression: A*exp(k*(v-d))
    A = 4
    k = -0.0555555555
    d = -65
    
    B = 1/k 
    
    beta = A * exp((v - d) / B)
    
    mtau = 1/(temp_adj*(alpha + beta))
    minf = alpha/(alpha + beta)
        
       
    
    ? Finished rate equations for gate: m
    
    ? Adding rate equations for gate: h
    
    ? Found a parameterised form of rate equation for alpha, using expression: A*exp(k*(v-d))
    A = 0.07
    k = -0.05
    d = -65
    
    B = 1/k 
    
    alpha = A * exp((v - d) / B)
    
    
    ? Found a parameterised form of rate equation for beta, using expression: A/(1 + exp(-k*(d-v)))
    A = 1
    k = -0.1
    d = -35
    
    B = 1/k 
    
    beta = A / (exp((v - d) / B) + 1)
    
    htau = 1/(temp_adj*(alpha + beta))
    hinf = alpha/(alpha + beta)
        
       
    
    ? Finished rate equations for gate: h
}

FUNCTION vtrap(VminV0, B) {
    if (fabs(VminV0/B) < 1e-6) {
    vtrap = (1 + VminV0/B/2)
}else{
    vtrap = (VminV0 / B) /(1 - exp((-1 *VminV0)/B))
    }
}

UNITSON


