
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.4.1
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RA 3.0  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.0157   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]

*set_global	         EREST_ACT	-0.06  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high


// Cell mechanism: NaF (density: 0.0 mS um^-2)
// Cell mechanism: pas (density: 2.812149E-10 mS um^-2)
*set_compt_param     ELEAK -0.066  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 3.5559993  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]


*spherical 

soma none 0 0 0 21.597 NaF 0 

