
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.1.4
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global RA 1.0  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global CM 0.0090   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m?²]

*set_global	RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]

*set_global     EREST_ACT	-0.06  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high


// Cell mechanism: ih_CML (density: 3.090506E-10 mS um^-2)
// Cell mechanism: pas (density: 3.0E-9 mS um^-2)
*set_compt_param     ELEAK -0.088  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 0.3333333333333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]
*double_endpoint
Soma none 0.0 0.0 0.0 0.0 37.766 0.0 11.0 ih_CML .3090506  
*double_endpoint_off

