TITLE combination of NMDA synapse, Ca pump and KCa
:
: This combines NMDA/AMPA synapse with depression (Alon Poslky, 2007), the calcium ATPase
: (Alain Destexhe, 1992) and the calcium dependent potassium channel (Zach Mainen, 1995).
: Ca Ion flux is not modelled and all the conductances are scaled to represent the volume
: of the compartment used for fitting the shape of NMDA spikes in Larkum et al 2009. 
: The goal is to replicate the results of glutamate200 point process in Larkum et al. 2009.
: It is assumed that each synapse makes an additive contribution to the total KCa 
: conductance. I.e. interactions between synapses are assumed to
: not contribute to the Ca dependent response. This assumption can be weakened by reducing
: the level KCa conductance, or Ra. This is probably more realistic
: when distributed inputs are used. The combined point process is also independent of the
: local segment volume, because everything is scaled to replicate the results from
: glutamate200.


NEURON {
	POINT_PROCESS glutamatecad2kca
	NONSPECIFIC_CURRENT i  : this is the total current generated by the synapse
	NONSPECIFIC_CURRENT iKCa	: this is the current generated by KCa channels

	RANGE e ,gmax,local_v, i	
	RANGE g, gnmda, inmda, ca_influx, ca
	RANGE n, gk, iKCa
	RANGE ninf, ntau, tinc


	GLOBAL ek
	GLOBAL Ra, Rb, caix, gbar
	GLOBAL q10, temp, tadj, vmin, vmax
	
	
	GLOBAL nglut,gama,tau1,tau2,tau_ampa,taur,depth,cainf
	GLOBAL NMDAswitch,ntar


}

UNITS {
	(nA) 	= (nanoamp)
	(mV)	= (millivolt)
	(nS) 	= (nanomho)
	(mM)    = (milli/liter)
        F	= 96480 (coul)
        R       = 8.314 (volt-coul/degC)
    	FARADAY = (faraday) (coulomb)
    (pS) = (picosiemens)
	(um) = (micron)
	(mA) = (milliamp)

}

PARAMETER {
	gmax=1	(nS)
	e= 0.0	(mV)
	tau1=70 (ms)	:90 :
	tau2=3:5	(ms) 
	tau_ampa=1	(ms)	
	nglut=0.3:0.25 	:(/mM)	
	gama=0.08 	(/mV) 
	dt (ms)
	ntar= 1	:NMDA to AMPA ratio
	v		(mV)
	gnmda
	inmda	
	NMDAswitch = 1
	
	depth	= .1	(um)		: depth of shell
	: area	= 0.618*2*(78.4871/11)*3.14159265*(1/100000000)		(cm2)
	taur	= 80	(ms)		: rate of calcium removal, changed from 200 to 80 (H.Markram)
	cainf	= 100e-6(mM)
	

	gbar = 40.0 	(pS)	: 0.03 mho/cm2
	cai  		(mM)
	caix = 4										
	Ra   = 0.05	(/ms)		: max act rate  
	Rb   = 0.1	(/ms)		: max deact rate 
	celsius		(degC)
	temp = 23	(degC)		: original temp 	
	q10  = 2.3			: temperature sensitivity
	vmin = -120	(mV)
	vmax = 100	(mV)	
	ek   = -87	(mV)


}

ASSIGNED { 
    i		(nA)	
	local_v	(mV):local voltage
	
	ca_influx 		(mA)
	drive_channel	(mM/ms)
	
	
	a		(/ms)
	b		(/ms)
	iKCa 		(nA)
	gk		(pS)
	ninf
	ntau 		(ms)	
	tadj
	tinc

	
}

STATE {
	g
	A (nS)
	B (nS)
	ca		(mM)
	
	n

}

INITIAL {

	g=0
	A=0
	B=0
	ca=cainf
	
	n = ninf


}   

LOCAL nexp 
LOCAL tinc

BREAKPOINT {  
    
	:LOCAL gnmda, inmda
	SOLVE state METHOD cnexp
	
	:this loop was used only to generate the spike train
	:state_discontinuity operations are moved to the NET_RECEIVE block
	:FROM count=0 TO Nspike-1 {
	:	IF(at_time(count*Tspike+del)){
	:		state_discontinuity( A, A+ gmax)
	:		state_discontinuity( B, B+ gmax)
	:		state_discontinuity( gampa, gampa+ gmax/ntar)
	:	}
	:}
	
	
	gnmda=(A-B)/(1+nglut*exp(-gama*v) )	
	inmda =(1e-3)* gnmda * 1 * (v-e) * NMDAswitch
	ca_influx=(inmda/10)
	i= (1e-3)*g* (v- e) + inmda + inmda/10
	local_v=v
	
	a = Ra * ca^caix
    b = Rb
    ntau = 1/(a+b)
	ninf = a*ntau
    tadj = q10^((celsius - temp)/10)
    tinc = -dt * tadj
    nexp = 1 - exp(tinc/ntau)
    
    n = n + nexp*(ninf-n)
	gk = tadj*gbar*n
	iKCa = (1e-6) * gk * (v - ek)    
	
	
}


DERIVATIVE state {	

	drive_channel =  - (10000) * ca_influx / (2 * FARADAY * depth)
	if (drive_channel <= 0.) { drive_channel = 0. }	: cannot pump inward
	ca'=drive_channel*72.2 + (cainf-ca)/taur
	

	g' = -g/tau_ampa
	A'=-A/tau1
	B'=-B/tau2	


}


NET_RECEIVE(weight (uS), tsyn (ms)) {

   state_discontinuity( A, A+ gmax)
   state_discontinuity( B, B+ gmax)
   state_discontinuity( g, g + gmax/ntar)
   
   tsyn = t

}





